FROM python:3.11-slim

ENV PIP_ROOT_USER_ACTION=ignore

WORKDIR /app

COPY src/api/ /app/
COPY models/trained/ /app/models/trained/

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000 9100

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]