apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: fastapi-latency-autoscaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: model
  minReplicaCount: 2
  maxReplicaCount: 6
  pollingInterval: 30
  cooldownPeriod: 300
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prom-kube-prometheus-stack-prometheus.monitoring.svc:9090
      metricName: fastapi_latency_p95
      query:
        histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{app="model"}[1m])) by (le))
      threshold: "0.5"
  - type: cpu
    metricType: Utilization
    metadata:
      value: "50"
     